=== joyyen/spec_xml_course_lab/lab-3-1.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="courses">
        <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element name="course">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="courseName"/>
                            <xs:element name="duration" type="xs:positiveInteger"/>
                            <xs:element name="date_begin" type="xs:string"/>
                            <xs:element name="teacher" type="xs:string"/>
                            <xs:element name="format" type="format"/>
                        </xs:sequence>      
                        <xs:attribute name="id" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="format">
        <xs:restriction base="xs:string">
            <xs:enumeration value="ordinary"/>
            <xs:enumeration value="open"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="courseName">
        <xs:restriction base="xs:string">
            <xs:minLength value="3"/>
            <xs:maxLength value="100"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== joyyen/spec_xml_course_lab/lab-3-1.xml
<?xml version="1.0" encoding="UTF-8"?>
<courses
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="lab-3-1.xsd"
>
<!-- Создайте XML-файл с именем lab3.xsd
Опишите схему для документа с данными о курсах: название курса, длительность (ак. часов), дата проведения, преподаватель.
Создайте файл lab3.xml с данными, соответствующий XML-схеме
подключите схему и убедитесь в корректности lab3.xml
Воспользуйтесь сервисами для проверки соответствия схемы и документа, и проверьте корректность XML-файла -->
    <course id='18085'>
        <name>Курс 1</name>
        <duration>10</duration>
        <date_begin>01.01.2021</date_begin>
        <teacher>Иванов Иван</teacher>
        <format>ordinary</format>
    </course>
    <course id='15005'>
        <name>Курс 22</name>
        <duration>8</duration>
        <date_begin>10.11.2021</date_begin>
        <teacher>Петров Пётр</teacher>
        <format>open</format>
    </course>
    <course id='12001'>
        <name>Курс 3</name>
        <duration>4</duration>
        <date_begin>05.08.2021</date_begin>
        <teacher>Васильев Василий</teacher>
        <format>open</format>
    </course>
</courses>
